#!/usr/bin/env bash
# Transfer a file from client to server
# Requirements: takes 4 parameters (the path of file to be transferred, the IP of server,
# the username scp connects withand the path to the SSH private key that scp uses)
# Displays the following if less than 3 parameters are passed:
#	Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

# check the number of parameters
if [ "$#" -eq 4 ]
then
	# do the necessary (via scp)
	scp -i "$4" -o stricthostkeychecking=no "$1" "$3"@"$2":~/
else
	echo "Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi #endif 
