#!/usr/bin/env bash
# Install and configure Nginx server (in remote server) to:
# Redirect permanently (301) /redirect_me to another page

# Update apt-get (first time use) and Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Alter index.html contents (tee -> reads from stdin and writes to stdout & file(s))
echo "Hello World!" | sudo tee /var/www/html/index.html
# permanently redirect (301) /redirect_me request to some other page/path
# use sed to: insert the redirect command just vefore line 53 in (file)
sudo sed -i '53i\rewrite ^/redirect_me https://www.youtube.con/watch?v=QH2-TGULwu4 permanent;' /etc/nginx/sites-available/default 
# once done, restart nginx to enable the changes
sudo service nginx restart
