#!/usr/bin/env bash
# Install and configure Nginx server (in remote server) to:
# Be listening on port 80 (does by default?)
# Return a page containing the string 'Hello World!' when queried at its root/ with a GET request using curl

# Update apt-get (first time use) and Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# reconfigure firewall to allow access to the nginx service
sudo ufw allow 'Nginx HTTP'

# configure (use defaults), just replace index.html's contents
echo "Hello World!" | sudo tee /var/www/html/index.html
# add a custom header, X-Served-By: server/hostname
sudo sed -i '49i\add_header X-Served-By "83517-web-02";' /etc/nginx/sites-available/default
# once done, restart nginx to enable the changes
sudo service nginx restart
