#!/usr/bin/env bash
# Installs and configures HAproxy on '1b-01' server with the following requirements:
# 	send traffic to web-01 and web-02
#	is manageable via an init script (i.e. via service ...)

sudo apt-get -y update
sudo apt-get -y install haproxy
# configure load balancing between web-01 and web-02 using roundrobin
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
sudo echo "\nfrontend nginx-apps\n\tbind *:80\n\tmode http\n\tdefault_backend nginx\nbackend nginx\n\tmode http\n\tbalance roundrobin\n\tserver 83517-web-01 54.82.173.163 check\n\tserver 83517-web-02 18.210.20.118 check" >>  etc/haproxy/haproxy.cfg
# restart server once configured for changes to take effect
sudo service haproxy restart
