#!/usr/bin/env bash
# Displays listening ports, only showing listening sockets &
# the PID and name of the program to which each socket belongs

# Display sockets infor
netstat -lp # listening sockets and PID
