#!/usr/bin/env bash
# Automate fixing an issue keeping an nginx server installation from listeming on port 80
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
