#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays the string "To infinity and beyond" indefinitely
# displays "I hate the kill command" when receiving a SIGTERM signal,
# "Y U no love me?!" when receiving a SIGINT signal &
# Deletes the file /var/run/myscript.pid and terminates iteself
# when receiving a SIGQUIT or SIGTERM signal

# trap to be trapped signals and display relevant messages
trap "echo 'I hate the kill command' ; rm /var/run/myscript.pid ; exit"  SIGTERM
trap "echo 'Y U no love me?!'"  SIGINT
trap " exit" SIGQUIT

# create file and write PID to it
echo $$ > /var/run/myscript.pid

# the infinite loop
while 'true'
do
	echo "To infinity and beyond"
	# sleep for a few secs
	sleep 2
done
