#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
str="Best School" # Note: no spaces when defining a variable in shell

# define the for loop
for ((i = 0; i < 10; i++))
do
	echo "$str" #protect against excess arguments error
done
