#!/usr/bin/env bash
# Displaying "Best School" 10 times using a while loop

count=0 # define a shell variable, again, no spaces between '='

# shell while loop, while count < 10
while [ $count -lt 10 ]
do
	echo "Best School" #print "Best School"
	count=$(( count + 1 ))  # increment count. count++ fails?
	# I thought it would work?
done

