#!/usr/bin/env bash
# Displays "Best School" 10 times, but for the 9th iteration
# displays the string then "Hi" on a new line
# uses a while loop

count=1

while [ $count -le 10 ]
do
	echo "Best School"
	# if count == 9, display "Hi" on a new line
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi #endif
	count=$(( count + 1 ))
done
