#!/usr/bin/env bash
# Displays information about a file , school

file="school"

# check that the file exists
if [ -e $file ]
then
	echo "school file exist"
# if true, check that its not empty
	if [ -s $file ]
	then
		echo "school file is not empty"
# if true (not empty), check that its a regular file
	else
		echo "school file is empty"
	fi #endif (file state case - empty or not)
	if [ -f $file ]
	then
		echo "school is a regular file"
	fi #endif (file type case)
else
	echo "school file does not exist"
fi #endif (existence case)
