#!/usr/bin/env bash
# Installs ufw firewall and sets up a few rules on web-01
# Requirements: configure ufw so that it blocks all incoming traffic except ssh, http and https

# update apt and install ufw
sudo apt-get -y update
sudo apt-get -y install ufw
# allow IPV6 (from /etc/default/ufw)
sed -i -e '$a\IPV6=yes\n' /etc/default/ufw
# disable and (re)enable ufw for changes to apply
sudo ufw disable && sudo ufw enable
# this should be the default upon installation, but just to be sure, deny all incoming traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing
# then allow only the desired: ssh(22), http(80) and https(443)
sudo ufw allow ssh 
sudo ufw allow http 
sudo ufw allow https
# re-anable ufw for new rules to apply
sudo ufw enable
# you can then check status to see if the changes now apply
sudo ufw status verbose
# or (status numbered) 
