#!/usr/bin/env bash
# Configures an Ubuntu server so that localhost resolves to 127.0.0.2 &
# facebook.com resolves to 8.8.8.8
# Note: Configuration is Docker conscious
sudo sed -i -e 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> //etc/hosts
